*! version 1.1.0 24jun2026
version 16.0
clear all
set more off

// =====================================================================
// rd2d_table_example.do
// Publication-quality table construction from rd2d estimation results
// Demonstrates two methods for exporting results to LaTeX and CSV
// Reference: Cattaneo, Titiunik, Yu (2025), Table 1
// =====================================================================

capture which rdbw2d
if _rc {
    foreach pkgpath in "rd2d-stata/ado" "rd2d-stata/pkg/ado" "ado" "pkg/ado" "../ado" "../pkg/ado" {
        capture confirm file "`pkgpath'/rdbw2d.ado"
        if !_rc {
            adopath ++ "`pkgpath'"
        }
    }
    foreach helppath in "rd2d-stata/help" "rd2d-stata/pkg/help" "help" "pkg/help" "../help" "../pkg/help" {
        capture confirm file "`helppath'/rdbw2d.sthlp"
        if !_rc {
            adopath ++ "`helppath'"
        }
    }
}

// ─── 1. Load package data and run estimation ────────────────────────────────

// Locate data files (works from multiple directory contexts)
local datadir ""
foreach dpath in "rd2d-stata/data" "data" "../data" "../rd2d-stata/data" {
    capture confirm file "`dpath'/data_rd2d.csv"
    if !_rc {
        local datadir "`dpath'"
        continue, break
    }
}
if "`datadir'" == "" {
    display as err "Cannot locate data_rd2d.csv; run from repository root or examples/ directory"
    exit 601
}

import delimited "`datadir'/data_rd2d.csv", varnames(1) clear asdouble
gen byte d = t == "TRUE"
drop t

// Use a subset of evaluation points spanning the boundary (9 points)
local atlist "0 50 0 40 0 27.5 0 15 0 0 10 0 22.5 0 35 0 47.5 0"

// Run rd2d with confidence bands (required for LBATE)
rd2d y x1 x2 d, at(`atlist') p(1) q(2) kernel(triangular) ktype(prod) ///
    bwselect(mserd) method(dpi) vce(hc1) bwcheck(52) masspoints(check) ///
    scaleregul(3) stdvars level(95) cbands repp(500)

// Store estimation results
tempname R
mat `R' = e(results)
local neval = e(neval)
local level = e(level)

// ─── 2. Method A: LaTeX table via file write (no dependencies) ──────────────
// Produces a standalone LaTeX tabular aligned with paper Table 1 format:
//   Point | (h1, h2) | Estimate | z | p-value | 95% CI

display _n as txt "=== Method A: LaTeX table output ==="

// Define evaluation point labels for display
local lbl1 "(0, 50)"
local lbl2 "(0, 40)"
local lbl3 "(0, 27.5)"
local lbl4 "(0, 15)"
local lbl5 "(0, 0)"
local lbl6 "(10, 0)"
local lbl7 "(22.5, 0)"
local lbl8 "(35, 0)"
local lbl9 "(47.5, 0)"

tempname fh
file open `fh' using "rd2d_table.tex", write replace

// Header
file write `fh' "% Generated by rd2d_table_example.do" _n
file write `fh' "% rd2d v1.1.0 -- Cattaneo, Titiunik, Yu (2025)" _n
file write `fh' "\begin{tabular}{lcccccc}" _n
file write `fh' "\toprule" _n
file write `fh' "Point & $(h_1, h_2)$ & Estimate & $z$ & $p$-value & \multicolumn{2}{c}{`level'\% CI} \\" _n
file write `fh' "\midrule" _n

// Loop over evaluation points
// e(results) columns: 1-2:b1,b2  3-4:Est_p,Se_p  5-6:Est_q,Se_q
//                     7:z  8:pvalue  9-10:CI_l,CI_u  11-12:CB_l,CB_u
//                     13-14:h01,h02  15-16:h11,h12  17-18:Nh0,Nh1
forvalues j = 1/`neval' {
    local est  = `R'[`j', 5]
    local z    = `R'[`j', 7]
    local pval = `R'[`j', 8]
    local ci_l = `R'[`j', 9]
    local ci_u = `R'[`j', 10]
    local h01  = `R'[`j', 13]
    local h02  = `R'[`j', 14]

    // Format p-value: use < 0.001 for very small values
    if `pval' < 0.001 {
        local pval_str "$< 0.001$"
    }
    else {
        local pval_str : display %5.3f `pval'
    }

    local row "$\hat\tau(\mathbf{b}_{`j'})$ `lbl`j'' & "
    local row "`row'(" %4.1f (`h01') ", " %4.1f (`h02') ") & "
    local row "`row'" %6.4f (`est') " & " %5.2f (`z') " & `pval_str' & "
    local row "`row'[" %6.4f (`ci_l') ", " %6.4f (`ci_u') "] \\"

    file write `fh' "`row'" _n
}

file write `fh' "\midrule" _n

// AATE row (equal-weighted average)
rd2d_aggregate, method(aate) level(`level')
local aate     = r(estimate)
local aate_se  = r(se)
local aate_z   = r(z)
local aate_p   = r(p)
local aate_cil = r(ci_lower)
local aate_ciu = r(ci_upper)

if `aate_p' < 0.001 {
    local aate_pstr "$< 0.001$"
}
else {
    local aate_pstr : display %5.3f `aate_p'
}

file write `fh' "$\hat\tau_{\mathrm{AATE}}$ & --- & " ///
    %6.4f (`aate') " & " %5.2f (`aate_z') " & `aate_pstr' & " ///
    "[" %6.4f (`aate_cil') ", " %6.4f (`aate_ciu') "] \\" _n

// LBATE row (largest boundary average treatment effect)
rd2d_aggregate, method(lbate) level(`level')
local lbate     = r(estimate)
local lbate_cil = r(ci_lower)
local lbate_ciu = r(ci_upper)

file write `fh' "$\hat\tau_{\mathrm{LBATE}}$ & --- & " ///
    %6.4f (`lbate') " & --- & --- & " ///
    "[" %6.4f (`lbate_cil') ", " %6.4f (`lbate_ciu') "] \\" _n

file write `fh' "\bottomrule" _n
file write `fh' "\end{tabular}" _n

file close `fh'
display as txt "  -> rd2d_table.tex written"
type "rd2d_table.tex"

// ─── 3. Method B: CSV export for flexibility ────────────────────────────────
// Useful for importing into Excel, R, or other tools

display _n as txt "=== Method B: CSV table output ==="

tempname fcsv
file open `fcsv' using "rd2d_table.csv", write replace

// CSV header
file write `fcsv' "point,b1,b2,h01,h02,estimate,se,z,pvalue,ci_lower,ci_upper" _n

// Data rows
forvalues j = 1/`neval' {
    local b1   = `R'[`j', 1]
    local b2   = `R'[`j', 2]
    local est  = `R'[`j', 5]
    local se   = `R'[`j', 6]
    local z    = `R'[`j', 7]
    local pval = `R'[`j', 8]
    local ci_l = `R'[`j', 9]
    local ci_u = `R'[`j', 10]
    local h01  = `R'[`j', 13]
    local h02  = `R'[`j', 14]

    file write `fcsv' "`j'," %9.4f (`b1') "," %9.4f (`b2') "," ///
        %9.4f (`h01') "," %9.4f (`h02') "," ///
        %9.6f (`est') "," %9.6f (`se') "," ///
        %9.4f (`z') "," %12.6e (`pval') "," ///
        %9.6f (`ci_l') "," %9.6f (`ci_u') _n
}

// Aggregate rows
file write `fcsv' "AATE,.,.,.,.,";
file write `fcsv' %9.6f (`aate') "," %9.6f (`aate_se') "," ///
    %9.4f (`aate_z') "," %12.6e (`aate_p') "," ///
    %9.6f (`aate_cil') "," %9.6f (`aate_ciu') _n
file write `fcsv' "LBATE,.,.,.,.,";
file write `fcsv' %9.6f (`lbate') ",.,.,.,";
file write `fcsv' %9.6f (`lbate_cil') "," %9.6f (`lbate_ciu') _n

file close `fcsv'
display as txt "  -> rd2d_table.csv written"
type "rd2d_table.csv"

// ─── 4. Method C: esttab/estout integration (requires estout package) ───────
// This approach repacks rd2d results into eclass for use with esttab.
// Only runs if estout is installed.

display _n as txt "=== Method C: esttab integration (optional) ==="

capture which esttab
if _rc {
    display as txt "  esttab not installed; skipping Method C."
    display as txt "  Install via: ssc install estout"
}
else {
    // Strategy: post point estimates and variance as eclass, then use esttab.
    // We store one "model" per evaluation point in estimates directory.

    estimates clear

    forvalues j = 1/`neval' {
        local est  = `R'[`j', 5]
        local se   = `R'[`j', 6]
        local h01  = `R'[`j', 13]
        local h02  = `R'[`j', 14]
        local nh0  = `R'[`j', 17]
        local nh1  = `R'[`j', 18]

        // Post as eclass
        tempname b V
        mat `b' = (`est')
        mat colnames `b' = tau
        mat `V' = (`se'^2)
        mat colnames `V' = tau
        mat rownames `V' = tau

        ereturn post `b' `V'
        ereturn scalar N = `nh0' + `nh1'
        ereturn scalar h01 = `h01'
        ereturn scalar h02 = `h02'
        ereturn local title "at`j': `lbl`j''"

        estimates store pt`j'
    }

    // Export all points in one table
    esttab pt*, cells(b(fmt(4)) se(par fmt(4))) ///
        stats(h01 h02 N, fmt(%6.1f %6.1f %9.0g) ///
        labels("Bandwidth h1" "Bandwidth h2" "N (effective)")) ///
        mtitles nostar nonumber compress ///
        title("RD Treatment Effect Estimates at Boundary Points")

    // LaTeX output
    esttab pt* using "rd2d_esttab.tex", replace ///
        cells(b(fmt(4)) se(par fmt(4))) ///
        stats(h01 h02 N, fmt(%6.1f %6.1f %9.0g) ///
        labels("Bandwidth $h_1$" "Bandwidth $h_2$" "$N$")) ///
        mtitles nostar nonumber booktabs ///
        title("RD Treatment Effect Estimates at Boundary Points")

    display as txt "  -> rd2d_esttab.tex written via esttab"
    estimates clear
}

// ─── Report ─────────────────────────────────────────────────────────────────
display _n as txt "=== Table example complete ==="
display as txt "  Evaluation points: " as res "`neval'"
display as txt "  AATE estimate:     " as res %9.6f `aate'
display as txt "  LBATE estimate:    " as res %9.6f `lbate'
display as txt "  Files created: rd2d_table.tex, rd2d_table.csv"

di as txt "EXIT:0"
